######################################################################################
#                       THIS IS SAMPLE OF THE CONFIGURATION                          #
# IT'S NOT A DEFAULT CONFIGURATION, IT'S JUST A REFERENCE TO ALL OPTIONS AND PLUGINS #
#       MORE DOCS CAN BE FOUND HERE: <https://roadrunner.dev/docs/intro-config>      #
######################################################################################

# Production usage guide: https://roadrunner.dev/docs/app-server-production/2.x/en

# Hint: RR will replace any config options using reference to environment variables,
# eg.: `option_key: ${ENVIRONMENT_VARIABLE_NAME}`.

# Important: TCP port numbers for each plugin (rpc, http, etc) must be unique!

# RR configuration version
version: "3"

# HTTP plugin settings.
http:
    # Host and port to listen on (eg.: `0.0.0.0:8080`).
    #
    # This option is required.
    address: 0.0.0.0:80

    # override http error code for the internal RR errors
    #
    # Default: 500
    internal_error_code: 500

    # HTTP access logs
    #
    # Default: false
    access_logs: false

    # Maximal incoming request size in megabytes. Zero means no limit.
    #
    # Default: 0
    max_request_size: 256

    # Send raw body (unescaped) to the PHP worker for the application/x-www-form-urlencoded content type
    #
    # Optional, default: false
    raw_body: false

    # Middlewares for the http plugin, order is important. Allowed values is: "headers", "gzip", "static", "sendfile",  [SINCE 2.6] -> "new_relic", [SINCE 2.6] -> "http_metrics", [SINCE 2.7] -> "cache"
    #
    # Default value: []
    middleware: ["headers", "gzip"]

    # Allow incoming requests only from the following subnets (https://en.wikipedia.org/wiki/Reserved_IP_addresses).
    #
    # Default: ["10.0.0.0/8", "127.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16",  "::1/128", "fc00::/7", "fe80::/10"]
    trusted_subnets:
        [
            "10.0.0.0/8",
            "127.0.0.0/8",
            "172.16.0.0/12",
            "192.168.0.0/16",
            "::1/128",
            "fc00::/7",
            "fe80::/10",
        ]

    # Settings for "headers" middleware (docs: https://roadrunner.dev/docs/middleware-headers/2.x/en).
    headers:
        # Allows to control CORS headers. Additional headers "Vary: Origin", "Vary: Access-Control-Request-Method",
        # "Vary: Access-Control-Request-Headers" will be added to the server responses. Drop this section for this
        # feature disabling.
        cors:
            # Controls "Access-Control-Allow-Origin" header value (docs: https://mzl.la/2OgD4Qf).
            #
            # Default: empty
            allowed_origin: "*"

            # Controls "Access-Control-Allow-Headers" header value (docs: https://mzl.la/2OzDVvk).
            #
            # Default: ""
            allowed_headers: "*"

            # Controls "Access-Control-Allow-Methods" header value (docs: https://mzl.la/3lbwyXf).
            #
            # Default: ""
            allowed_methods: "GET,POST,PUT,DELETE"

            # Controls "Access-Control-Allow-Credentials" header value (docs: https://mzl.la/3ekJGaY).
            #
            # Default: false
            allow_credentials: true

            # Controls "Access-Control-Expose-Headers" header value (docs: https://mzl.la/3qAqgkF).
            #
            # Default: ""
            exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"

            # Controls "Access-Control-Max-Age" header value in seconds (docs: https://mzl.la/2PCSdvt).
            #
            # Default: 0
            max_age: 600

        # Automatically add headers to every response.
        #
        # Default: <empty map>
        response:
            X-Powered-By: "RoadRunner"

    # Settings for "static" middleware (docs: https://roadrunner.dev/docs/middleware-static/2.x/en).
    static:
        # Path to the directory to serve
        #
        # Default: "." (current)
        dir: "."

        # File patterns to forbid
        #
        # Default: empty
        forbid: [""]

        # Etag calculation (base on the body CRC32)
        #
        # Default: false
        calculate_etag: false

        # Weak etag calculation (based only on the content-length CRC32)
        #
        # Default: false
        weak: false

    # Workers pool settings.
    pool:
        # Debug mode for the pool. In this mode, pool will not pre-allocate the worker. Worker (only 1, num_workers ignored) will be allocated right after the request arrived.
        #
        # Default: false
        debug: false

        # Override server's command
        #
        # Default: empty
        command: "php index.php"

        # How many worker processes will be started. Zero (or nothing) means the number of logical CPUs.
        #
        # Default: 0
        num_workers: 0

        # Maximal count of worker executions. Zero (or nothing) means no limit.
        #
        # Default: 0
        max_jobs: 0

        # [2023.3.10]
        # Maximum size of the internal requests queue. After reaching the limit, all additional requests would be rejected with error.
        #
        # Default: 0 (no limit)
        max_queue_size: 0

        # Timeout for worker allocation. Zero means 60s.
        #
        # Default: 60s
        allocate_timeout: 60s

        # Timeout for the reset timeout. Zero means 60s.
        #
        # Default: 60s
        reset_timeout: 60s

        # Timeout for the stream cancellation. Zero means 60s.
        #
        # Default: 60s
        stream_timeout: 60s

        # Timeout for worker destroying before process killing. Zero means 60s.
        #
        # Default: 60s
        destroy_timeout: 60s

        # Supervisor is used to control http workers (previous name was "limit", video: https://www.youtube.com/watch?v=NdrlZhyFqyQ).
        # "Soft" limits will not interrupt current request processing. "Hard"
        # limit on the contrary - interrupts the execution of the request.
        supervisor:
            # How often to check the state of the workers.
            #
            # Default: 1s
            watch_tick: 1s

            # Maximum time worker is allowed to live (soft limit). Zero means no limit.
            #
            # Default: 0s
            ttl: 0s

            # How long worker can spend in IDLE mode after first using (soft limit). Zero means no limit.
            #
            # Default: 0s
            idle_ttl: 10s

            # Maximal worker memory usage in megabytes (soft limit). Zero means no limit.
            #
            # Default: 0
            max_worker_memory: 128

            # Maximal job lifetime (hard limit). Zero means no limit.
            #
            # Default: 0s
            exec_ttl: 60s

    # SSL (Secure Sockets Layer) (TLS) settings (docs: https://roadrunner.dev/docs/app-server-https/2.x/en).
    ssl:
        # Host and port to listen on (eg.: `0.0.0.0:443`).
        #
        # Default: ":443"
        address: "0.0.0.0:443"

        # Use ACME certificates provider (Let's encrypt)
        acme:
            # Directory to use as a certificate/pk, account info storage
            #
            # Optional. Default: rr_cache
            certs_dir: rr_le_certs

            # User email
            #
            # Used to create LE account. Mandatory. Error on empty.
            email: you-email-here@email

            # Alternate port for the http challenge. Challenge traffic should be redirected to this port if overridden.
            #
            # Optional. Default: 80
            alt_http_port: 80

            # Alternate port for the tls-alpn-01 challenge. Challenge traffic should be redirected to this port if overridden.
            #
            # Optional. Default: 443.
            alt_tlsalpn_port: 443

            # Challenge types
            #
            # Optional. Default: http-01. Possible values: http-01, tlsalpn-01
            challenge_type: http-01

            # Use production or staging endpoint. NOTE, try to use staging endpoint to make sure, that everything works correctly.
            #
            # Optional, but for production should be set to true. Default: false
            use_production_endpoint: true

            # List of your domains to obtain certificates
            #
            # Mandatory. Error on empty.
            domains: []

        # Automatic redirect from http:// to https:// schema.
        #
        # Default: false
        redirect: true

        # Path to the cert file. This option is required for SSL working.
        #
        # This option is required.
        cert: /etc/ssl/site/server.crt

        # Path to the cert key file.
        #
        # This option is required.
        key: /etc/ssl/site/server.key

        # Client auth type (mTLS)
        #
        # This option is optional. Default value: no_client_certs. Possible values: request_client_cert, require_any_client_cert, verify_client_cert_if_given, require_and_verify_client_cert, no_client_certs
        client_auth_type: no_client_certs

    # HTTP/2 settings.
    http2:
        # HTTP/2 over non-encrypted TCP connection using H2C.
        #
        # Default: false
        h2c: false

        # Maximal concurrent streams count.
        #
        # Default: 128
        max_concurrent_streams: 128
