name: Publish Docker (shinsenter/php)

################################################################################
################################################################################

on:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches:
      - main

################################################################################
################################################################################

jobs:

################################################################################
################################################################################

  base_image:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        base:
          - ubuntu
        version:
          - focal
        platform:
          - linux/amd64
        name:
          - shinsenter/s6-ubuntu
    env:
      DOCKER_BUILDKIT: "1"
      BUILD_TAG: "main-${{ github.sha }}"
      OS_BASE: ${{ matrix.base }}
      OS_VERSION: ${{ matrix.version }}
      OS_PLATFORM: ${{ matrix.platform }}
      IMAGE_NAME: ${{ matrix.name }}
      IMAGE_TAG: ${{ matrix.image }}:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Cache layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-$BUILD_TAG
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:src/base/"
          push: false
          tags: ${IMAGE_TAG}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

################################################################################
################################################################################

  php_images:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        variation:
          - cli
          - fpm
          - fpm-apache
          - fpm-nginx
        version:
          - "7.4"
          - "8.0"
          - "8.1"
        base:
          - shinsenter/s6-ubuntu:focal
        platform:
          - linux/amd64
        name:
          - shinsenter/php
    env:
      DOCKER_BUILDKIT: "1"
      BUILD_TAG: "main-${{ github.sha }}"
      PHP_VERSION: ${{ matrix.version }}
      IMAGE_BASE: ${{ matrix.base }}
      IMAGE_NAME: ${{ matrix.name }}
      IMAGE_TAG: ${{ matrix.name }}:${{ matrix.version }}-${{ matrix.variation }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Cache layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-$BUILD_TAG
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:src/php/${{ matrix.variation }}/"
          push: false
          tags: ${IMAGE_TAG}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

################################################################################
################################################################################
